---
- name: Configuración completa del agente en Ubuntu
  hosts: Ubuntu-Agente
  gather_facts: false
  become: true
  tasks:
    # - name: Hacer apt update
    #   apt:
    #     update_cache: true

    - name: Instalar auditd
      apt:
        name: auditd
        state: present

    - name: Iniciar auditd
      service:
        name: auditd
        state: started
        enabled: true

    # - name: Copiar ossec.conf a la máquina remota
    #   copy:
    #     src: ./scripts_ansible/ossec.conf
    #     dest: /var/ossec/etc/ossec.conf
    #     mode: '0660'

    - name: Copiar script de configuración de reglas de auditd a la máquina remota
      copy:
        src: ./scripts_ansible/configurar_agente.sh
        dest: /tmp/configurar_agente.sh
        mode: '0755'

    - name: Ejecutar el script de configuración del agente en la máquina remota
      command: /tmp/configurar_agente.sh
      register: script_output

    - name: Debug salida del script
      debug:
        msg: "La salida del script es: {{ script_output.stdout }}"

    - name: Reiniciar el agente de Wazuh
      service:
        name: wazuh-agent
        state: restarted

    - name: Reiniciar auditd
      service:
        name: auditd
        state: restarted
