---
- name: Configuración completa del servidor Wazuh manager
  hosts: Amazon-Wazuh-Server
  gather_facts: false
  become: true
  tasks:
    - name: Esperar a que la conexión SSH esté disponible
      wait_for_connection:
        delay: 0
        timeout: 60

    - name: Escribir IP del servidor en archivo local
      copy:
        content: "{{ private_ip }}"
        dest: /tmp/ip_server.txt
      delegate_to: localhost
      become: false

    - name: Copiar script instalación del servidor a la máquina remota
      copy:
        src: ./scripts_ansible/instala_server.sh
        dest: /tmp/instala_server.sh
        mode: '0755'

    - name: Ejecutar el script de instalación del servidor en la máquina remota
      command: /tmp/instala_server.sh
      become: true
      register: script_output

    - name: Comprobar si el script se ha ejecutado correctamente
      fail:
        msg: "El script ha fallado con el error: {{ script_output.stderr }}"
      when: script_output.rc != 0

    - name: Obtener el password de admin para hacer login en Wazuh
      shell: |
        tar -xf wazuh-install-files.tar -O wazuh-install-files/wazuh-passwords.txt \
        | grep admin -A 1 \
        | sed -n '2p' \
        | awk '{print $2}'
      register: admin_password_output        

    - name: Imprimir el password
      debug:
        msg: "El password para 'admin' es {{ admin_password_output.stdout }}"

    - name: Copiar reglas_webshell.xml a la máquina remota
      copy:
        src: ./scripts_ansible/reglas_webshell.xml
        dest: /var/ossec/etc/rules/reglas_webshell.xml
        owner: wazuh
        group: wazuh
        mode: '0660'

    - name: Copiar local_decoder.xml a la máquina remota
      copy:
        src: ./scripts_ansible/local_decoder.xml
        dest: /var/ossec/etc/decoders/local_decoder.xml
        owner: wazuh
        group: wazuh
        mode: '0660'

    - name: Reiniciar el agente de Wazuh
      service:
        name: wazuh-manager
        state: restarted
