---
- name: Ejecutar instalación agente Windows
  hosts: Windows-Agente
  gather_facts: false
  tasks:
    - name: Descargar paquete instalación
      win_get_url:
        url: https://packages.wazuh.com/4.x/windows/wazuh-agent-4.7.5-1.msi
        dest: /tmp/wazuh-agent-4.8.0-1.msi
        mode: 0644

    - name: Read IP address from local file
      slurp:
        src: /tmp/ip_server.txt
      register: ip_server_content

    - name: Install Wazuh Agent
      win_shell: |
        $ip_address = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('{{ ip_server_content.content | b64decode }}'))
        Start-Process msiexec.exe -ArgumentList "/i C:\Temp\wazuh-agent-4.7.5-1.msi /q WAZUH_MANAGER=$ip_address" -Wait