---
- name: Instalación del agente en Ubuntu
  hosts: Ubuntu-Agente
  gather_facts: false
  become: true
  tasks:
    - name: Traerse el archivo local con la ip del server para utilizarla en la instalación
      copy:
        src: /tmp/ip_server.txt
        dest: /tmp/ip_server.txt

    - name: Copiar script instalación del agente a la máquina remota Ubuntu
      copy:
        src: ./scripts_ansible/instala_agente.sh
        dest: /tmp/instala_agente.sh
        mode: '0755'

    - name: Ejecutar el script de instalación del agente en la máquina remota
      command: /tmp/instala_agente.sh
      become: true
      register: script_output

    - name: Check if the script executed successfully
      fail:
        msg: "The script failed with error: {{ script_output.stderr }}"
      when: script_output.rc != 0
