---
- name: Copy and execute a bash script
  hosts: all
  gather_facts: true
  tasks:
    - name: Instalar servidor en Amazon Linux
      block: 

      - name: Copiar script instalación del servidor a la máquina remota
        copy:
          src: ./scripts_ansible/instala_server.sh
          dest: /tmp/instala_server.sh
          mode: '0755'
          
      - name: Ejecutar el script de instalación del servidor en la máquina remota
        command: /tmp/instala_server.sh
        become: true      
      when: "'amazon' in inventory_hostname | lower"

    - name: Instalar agente en Ubuntu
      block:
      - name: Copiar script instalación del agente a la máquina remota
        copy:
          src: ./scripts_ansible/instala_agente.sh
          dest: /tmp/instala_agente.sh
          mode: '0755'
      - name: Ejecutar el script de instalación del agente en la máquina remota
        command: /tmp/instala_agente.sh {{ lookup('env', 'IP_SERVER')}}
        become: true      
      when: 
      - "'ubuntu' in inventory_hostname | lower"

