---
- name: Instalar apache
  hosts: Ubuntu-Agente
  gather_facts: false
  become: true
  tasks:
    - name: Hacer apt update
      apt:
        update_cache: true

    - name: Instalar apache
      apt:
        name: apache2
        state: present

    - name: Iniciar apache
      service:
        name: apache2
        state: started

    - name: Instalar PHP 8.3 sin los paquetes remocendados
      apt:
        name: php8.3
        state: present
        install_recommends: false

    - name: Copiar webshell.php a la máquina remota
      copy:
        src: ./scripts_ansible/webshell.php
        dest: /var/www/html/webshell.php
        owner: www-data
        group: www-data
        mode: '0644'