---
- name: Ejecutar instalación agente Windows
  hosts: Windows-Agente
  gather_facts: false
  tasks:
    - name: Comprueba si el agente de Wazuh ya está instalado
      win_stat:
        path: 'C:\Program Files (x86)\ossec-agent'
      register: wazuh_agent_check

    - name: Muestra mensaje al respecto de la instalación
      debug:
        msg: "Wazuh agent ya está instalado."
      when: wazuh_agent_check.stat.exists

    - block:
        - name: Leer dirección IP de archivo local
          ansible.builtin.set_fact:
            ip_server_content: "{{ lookup('ansible.builtin.file', '/tmp/ip_server.txt') }}"

        - name: Crea un directorio temporal
          win_tempfile:
            state: directory
          register: temp_dir

        - name: Descarga archivo de instalación del agente de Wazuh a directorio temporal
          win_get_url:
            url: https://packages.wazuh.com/4.x/windows/wazuh-agent-4.7.5-1.msi
            dest: "{{ temp_dir.path }}\\wazuh-agent-4.7.5-1.msi"

        - name: Configura la política para permitir la ejecución de scripts
          win_shell: Set-ExecutionPolicy Bypass -Scope Process -Force

        - name: Instalar agente de Wazuh
          win_shell: |
            Start-Process -FilePath "{{ temp_dir.path }}\\wazuh-agent-4.7.5-1.msi" -ArgumentList "/q", "WAZUH_MANAGER={{ ip_server_content }}" -Wait
          args:
            executable: powershell.exe

        - name: Iniciar agente
          ansible.windows.win_service:
            name: Wazuh
            state: started
      when: not wazuh_agent_check.stat.exists