all:
  hosts:
    Amazon-Wazuh-Server:
      ansible_host: 54.174.139.178
      ansible_user: ec2-user
      private_ip: 172.31.51.251
    Debian-Atacante:
      ansible_host: 3.81.103.46
      ansible_user: admin
      private_ip: 172.31.45.11
    Ubuntu-Agente:
      ansible_host: 54.173.8.242
      ansible_user: ubuntu
      private_ip: 172.31.33.16
    Windows-Agente:
      ansible_connection: winrm
      ansible_host: 54.88.112.209
      ansible_password: SecureP@ssword123
      ansible_user: AdminUser
      ansible_winrm_port: 5986
      ansible_winrm_server_cert_validation: ignore
      ansible_winrm_transport: basic
      private_ip: 172.31.49.108
  vars:
    ansible_private_key_file: ./despliegue_wazuh.pem
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
