all:
  hosts:
    Amazon-Wazuh-Server:
      ansible_host: 54.87.137.135
      ansible_ssh_user: ec2-user
    Debian-Atacante:
      ansible_host: 52.90.199.40
      ansible_ssh_user: admin
    Ubuntu-Agente:
      ansible_host: 3.80.222.155
      ansible_ssh_user: ubuntu
    Windows-Agente:
      ansible_host: 3.87.239.248
      ansible_ssh_user: admin
  vars:
    ansible_private_key_file: ./despliegue_wazuh.pem
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
