all:
  hosts:
    Amazon-Wazuh-Server:
      ansible_host: 54.197.87.169
      ansible_ssh_user: ec2-user
    Debian-Atacante:
      ansible_host: 54.234.161.173
      ansible_ssh_user: admin
    Ubuntu-Agente:
      ansible_host: 54.91.100.191
      ansible_ssh_user: ubuntu
    Windows-Agente:
      ansible_host: 52.87.255.114
      ansible_ssh_user: admin
  vars:
    ansible_private_key_file: ./despliegue_wazuh.pem
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
