all:
  hosts:
    Amazon-Wazuh-Server:
      ansible_host: 3.208.29.85
      ansible_ssh_user: ec2-user
    Debian-Atacante:
      ansible_host: 52.87.167.85
      ansible_ssh_user: admin
    Ubuntu-Agente:
      ansible_host: 54.172.5.7
      ansible_ssh_user: ubuntu
    Windows-Agente:
      ansible_host: 54.221.108.206
      ansible_ssh_user: admin
  vars:
    ansible_private_key_file: ./despliegue_wazuh.pem
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
