all:
  hosts:
    Amazon-Wazuh-Server:
      ansible_host: 52.23.222.138
      ansible_user: ec2-user
      private_ip: 172.31.46.1
    Debian-Atacante:
      ansible_host: 54.152.119.248
      ansible_user: admin
      private_ip: 172.31.88.212
    Ubuntu-Agente:
      ansible_host: 54.165.218.186
      ansible_user: ubuntu
      private_ip: 172.31.86.13
    Windows-Agente:
      ansible_connection: winrm
      ansible_host: 34.239.187.56
      ansible_password: SecureP@ssword123
      ansible_user: AdminUser
      ansible_winrm_port: 5986
      ansible_winrm_server_cert_validation: ignore
      ansible_winrm_transport: basic
      private_ip: 172.31.43.145
  vars:
    ansible_private_key_file: ./despliegue_wazuh.pem
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
