all:
  hosts:
    Amazon-Wazuh-Server:
      ansible_host: 54.236.53.26
      ansible_ssh_user: ec2-user
    Debian-Atacante:
      ansible_host: 54.91.129.246
      ansible_ssh_user: admin
    Ubuntu-Agente:
      ansible_host: 54.234.138.163
      ansible_ssh_user: ubuntu
    Windows-Agente:
      ansible_host: 34.229.186.132
      ansible_ssh_user: admin
  vars:
    ansible_private_key_file: ./despliegue_wazuh.pem
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
