all:
  hosts:
    Amazon-Wazuh-Server:
      ansible_host: 54.81.16.84
      ansible_ssh_user: ec2-user
      private_ip: 172.31.46.1
    Debian-Atacante:
      ansible_host: 3.95.200.100
      ansible_ssh_user: admin
      private_ip: 172.31.88.212
    Ubuntu-Agente:
      ansible_host: 44.210.128.99
      ansible_ssh_user: ubuntu
      private_ip: 172.31.86.13
    Windows-Agente:
      ansible_connection: winrm
      ansible_host: 52.201.133.206
      ansible_password: SecureP@ssword123
      ansible_ssh_user: AdminUser
      ansible_user: AdminUser
      ansible_winrm_port: 5986
      ansible_winrm_server_cert_validation: ignore
      ansible_winrm_transport: basic
      private_ip: 172.31.43.145
  vars:
    ansible_private_key_file: ./despliegue_wazuh.pem
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
