all:
  hosts:
    Amazon-Wazuh-Server:
      ansible_host: 34.238.161.240
      ansible_ssh_user: ec2-user
      private_ip: 172.31.40.184
    Debian-Atacante:
      ansible_host: 18.215.149.131
      ansible_ssh_user: admin
      private_ip: 172.31.18.94
    Ubuntu-Agente:
      ansible_host: 54.145.27.21
      ansible_ssh_user: ubuntu
      private_ip: 172.31.22.27
    Windows-Agente:
      ansible_connection: winrm
      ansible_host: 52.90.224.189
      ansible_password: SecureP@ssword123
      ansible_ssh_user: AdminUser
      ansible_user: AdminUser
      ansible_winrm_port: 5986
      ansible_winrm_server_cert_validation: ignore
      ansible_winrm_transport: ntlm
      private_ip: 172.31.40.107
  vars:
    ansible_private_key_file: ./despliegue_wazuh.pem
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
